[package]
name = "generator"
version = "0.1.0"
edition = "2024"

[dependencies]
genlib = { path = "../lib" }
clap = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
